[0m01:06:29.455624 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be8ad2c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be75bf7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be75bf760>]}


============================== 01:06:29.458484 | bd1f8393-f269-4261-a47c-c788358a410d ==============================
[0m01:06:29.458484 [info ] [MainThread]: Running with dbt=1.5.2
[0m01:06:29.459259 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m01:06:29.459886 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/vscode/.dbt')}
[0m01:06:29.460397 [info ] [MainThread]: Creating dbt configuration folder at 
[0m01:07:01.909237 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m01:08:21.225360 [info ] [MainThread]: Profile coffee_shop_marcel written to /home/vscode/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:08:21.226803 [info ] [MainThread]: 
Your new dbt project "coffee_shop_marcel" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:08:21.228105 [debug] [MainThread]: Command `dbt init` succeeded at 01:08:21.227893 after 111.78 seconds
[0m01:08:21.228883 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be8ad2c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be5a96980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2be5a96a10>]}
[0m01:08:21.229624 [debug] [MainThread]: Flushing usage events
[0m01:10:19.072453 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e2908ab60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e2b13e290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e27bb7df0>]}


============================== 01:10:19.075235 | 5e456bd3-6218-4380-90c8-891d3a2c7953 ==============================
[0m01:10:19.075235 [info ] [MainThread]: Running with dbt=1.5.2
[0m01:10:19.076113 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m01:10:19.076949 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/aec-self-study-marcel/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:10:19.077995 [debug] [MainThread]: Command `dbt ls` failed at 01:10:19.077799 after 0.01 seconds
[0m01:10:19.078582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e2908ab60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e27bb7e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3e27bb75e0>]}
[0m01:10:19.079184 [debug] [MainThread]: Flushing usage events
[0m03:08:22.078623 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e6512bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e4f93c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e4f93be0>]}


============================== 03:08:22.081707 | 8d9a2042-7b93-4381-bc66-66010908ce40 ==============================
[0m03:08:22.081707 [info ] [MainThread]: Running with dbt=1.5.2
[0m03:08:22.082610 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m03:08:22.083404 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/aec-self-study-marcel/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:08:22.084443 [debug] [MainThread]: Command `dbt run` failed at 03:08:22.084256 after 0.02 seconds
[0m03:08:22.085010 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e6512bc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e4f93af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f29e4f93b80>]}
[0m03:08:22.085724 [debug] [MainThread]: Flushing usage events
